"""Named constants for spark_plan_viz — replaces all magic numbers."""

MAX_DISPLAY_COLUMNS = 5
MAX_DISPLAY_FUNCTIONS = 3
MAX_DISPLAY_FILTERS = 3
MAX_DISPLAY_GROUPING_KEYS = 3
NODE_NAME_TRUNCATION = 25
TEXT_TRUNCATION = 30
IFRAME_HEIGHT = 800
